# Generated by Django 4.0.4 on 2022-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_works', '0002_alter_work_metadata_iswc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_metadata',
            name='iswc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
